### ISSUE TITLE
New release possible?

### ISSUE THREAD

**Issue by zvickery** [postgres/pgagent#6]
The bug fixed by https://github.com/postgres/pgagent/commit/f9bf1ccb27ebcfce00e7a6d467bc0e1b5ee9555e is critical on some platforms.  Is it possible to make this a release so it can be officially packaged?

**Comment by CWnfo** [comment]
+1
please add a 3.4.0.1 or something just for this bug - it's even not easy build on ubuntu server

**Comment by Tostino** [comment]
Causes a crash of pgagent for me whenever there is a connection loss between pgagent and postgresql, or a restart of postgresql.  Debian 7 / 8.
